name: Docker

on:
  push:
    branches:
      - master
      - dev
    tags:
      - "*"
  schedule:
    # Mondays 4AM UTC
    - cron: "0 4 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true

      - name: Set Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
            name=trailofbits/eth-security-toolbox,enable=${{ github.repository == 'trailofbits/eth-security-toolbox' }}
          tags: |
            type=schedule
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=ref,event=tag
            type=ref,event=branch,prefix=testing-
            type=edge

      - name: GitHub Container Registry Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Hub Login
        uses: docker/login-action@v3
        if: github.repository == 'trailofbits/eth-security-toolbox'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64/v8
          target: toolbox
          file: Dockerfile
          pull: true
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
